# Schema for the configuration files of the Content Block module.

block_content.type.*:
  type: config_entity
  label: 'Block type settings'
  mapping:
    id:
      type: machine_name
      label: 'ID'
    label:
      type: required_label
      label: 'Label'
    revision:
      type: boolean
      label: 'Whether a new revision should be created by default'
    description:
      type: text
      label: 'Description'
      nullable: true
      constraints:
        NotBlank:
          allowNull: true
  constraints:
    FullyValidatable: ~

# @see \Drupal\block_content\Plugin\Block\BlockContentBlock
# @eee \Drupal\block_content\Plugin\Derivative\BlockContent
block.settings.block_content:*:
  type: block_settings
  label: 'Content block'
  constraints:
    FullyValidatable: ~
  mapping:
    # @see \Drupal\block_content\Plugin\Block\BlockContentBlock::defaultConfiguration()
    status:
      deprecated: "The 'status' setting for content blocks is deprecated in drupal:11.3.0 and is removed from drupal 12.0.0. It was unused, so there is no replacement. See https://www.drupal.org/node/3499836."
      type: boolean
      label: 'Status'
    info:
      deprecated: "The 'info' setting for content blocks is deprecated in drupal:11.3.0 and is removed from drupal 12.0.0. It was unused, so there is no replacement. See https://www.drupal.org/node/3499836."
      type: label
      label: 'Admin info'
    view_mode:
      type: string
      label: 'View mode'
      constraints:
        ConfigExists:
          prefix: core.entity_view_mode.block_content.
